### ISSUE TITLE
500 Error when trying to submit an RSS file.

### ISSUE THREAD

**Issue by unwaivering** [jtanza/rufus#4]
I'm trying to submit the URL of a subscriptions.xml file I uploaded to Dropbox. I'm getting a 500 error after I submit. It isn't adding the feeds from the file and just giving me an error either. When I go back to check my account, the feeds aren't there. For some reason the attachment isn't cooperating with me and my screen reader so here's a link to the file. https://www.dropbox.com/s/yz8pxhieqicf3dd/export_1522113411.xml?dl=1

**Comment by jtanza** [comment]
Having some trouble opening from the link provided, could you try re-sending the problematic sources?
